---
source: crates/ruff_linter/src/rules/flake8_pytest_style/mod.rs
---
PT017.py:27:9: PT017 Found assertion on exception `e` in `except` block, use `pytest.raises()` instead
   |
25 |         something()
26 |     except Exception as e:
27 |         assert e.message, "blah blah"
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PT017
   |
